version: '3.8'

services:
  # Django Web Service
  web:
    build: 
      context: ..
      dockerfile: ./Backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
      - mongo_db
    environment:
      - DEBUG=1  # Set to 0 in production

  # MySQL Database Service
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'investors_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # MongoDB Database Service
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: 'investment_mongo_db'
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # PhpMyAdmin for MySQL Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_USER: 'user'
      PMA_PASSWORD: 'password'
    ports:
      - "8080:80"
    depends_on:
      - mysql_db

  # Mongo Express for MongoDB Management
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db

# Volumes for data persistence
volumes:
  mysql_data:
  mongo_data:
